version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  build:
    docker:
    - image: circleci/openjdk:11-jdk
    steps:
    - checkout
    - aws-s3/copy:
        arguments: --acl public-read
        from: c8oProject.yaml
        to: 's3://c8oforms/'
    - run: |
         echo "ls -lh"
         ls -lh
#        sh gradlew --no-daemon --stacktrace --info car downloadNativeBuild
#        echo "ls -lh"
#        ls -lh
#        echo "ls -lh build"
#        ls -lh build
#        echo "ls -lh DisplayObjects/mobile/build"
#        ls -lh DisplayObjects/mobile/build
workflows:
  version: 2
  all:
    jobs:
    - build