version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - checkout
    - run: |
        sh gradlew --no-daemon --stacktrace --info car
        ls -lh
        ls -lh build
        ls -lh DisplayObjects/mobile/build
workflows:
  version: 2
  all:
    jobs:
    - build